name: ${name}
main: nl.giantit.minecraft.${package}.${name}
version: ${version}-${build}
authors: [Giant, Jake6177]
depend: [GiantCore]

commands:
    pm:
        description: GiantPM
        usage: /pm help

permissions:
    giantpm.admin:
        default: false
        children:
            giantpm.user: true
            giantpm.admin.fuckprivacy: true
            giantpm.message.admin: true
            giantpm.message.nolimit: true
    giantpm.user:
        default: false
        children:
            giantpm.commands.mute: true
            giantpm.commands.unmute: true
            giantpm.commands.invite: true
            giantpm.commands.join: true
            giantpm.commands.members: true
            giantpm.commands.part: true
            giantpm.message.normal: true
            giantpm.commands.state: true
    giantpm.message.admin:
        description: Enables GiantPM messaging to configurable admin group
        default: false
    giantpm.admin.fuckprivacy:
        description: Enables admin to override conversation privacy settings
        default: false
    giantpm.commands.invite:
        description: Enables GiantPM invite command
        default: false
    giantpm.commands.join:
        description: Enables GiantPM join command
        default: false
    giantpm.commands.members:
        description: Enables GiantPM members command
        default: false
    giantpm.commands.mute:
        description: Enables GiantPM mute command
        default: false
    giantpm.message.normal:
        description: Enables general GiantPM messaging
        default: false
    giantpm.commands.part:
        description: Enables GiantPM part command
        default: false
    giantpm.commands.state:
        description: Enables GiantPM state command
        default: false
    giantpm.message.nolimit:
        description: Enables GiantPM messaging to unlimited amount of players
        default: false
