name: GiantPM
main: nl.giantit.minecraft.giantpm.GiantPM
version: 2.4.DEV-SNAPSHOT-2
authors: [Giant]
depend: [GiantCore]
commands:
    pm:
        desription: GiantPM
        usage: /pm help
permissions:
    giantpm.admin.fuckprivacy:
        description: Enables admin to override conversation privacy settings
        default: op