name: GiantPM
main: nl.giantit.minecraft.GiantPM.GiantPM
version: 2.1
commands:
    pm:
        desription: GiantPM
        usage: /pm help
permissions:
    giantpm.admin.fuckprivacy:
        description: Enables admin to override conversation privacy settings
        default: op