name: $name
main: nl.giantit.minecraft.$name.$name
version: $version-$build
commands:
    pm:
        desription: GiantPM
        usage: /pm help
permissions:
    giantpm.admin.fuckprivacy:
        description: Enables admin to override conversation privacy settings
        default: op